import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Advent of Coding</h1>

        <p className={styles.description}>
          <code className={styles.code}>
            All mini projects are coded using JavaScript and SCSS.
          </code>
        </p>

        <div className={styles.grid}>
          <a href="/pomodorotimer" className={styles.card}>
            <h2>Pomodoro Timer &rarr;</h2>
            <img src="" />
          </a>

          <a href="/" className={styles.card}>
            <h2>Challenge 2 &rarr;</h2>
            <img src="" />
          </a>

          <a href="/" className={styles.card}>
            <h2>Challenge 3 &rarr;</h2>
            <img src="" />
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by{" "}
          <span className={styles.logo}>
            <a href="http://tracewhite.dev">Trace White</a>
          </span>
        </a>
      </footer>
    </div>
  );
}
